In [ ]:
#kanneeswari .P


In [1]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
array = np.array([10,20,30,40,50])
print("Numpy array:")
print(array)

Numpy array:
[10 20 30 40 50]


In [4]:
print("shape of array:")
print(array.shape)


shape of array:
(5,)


In [5]:
import pandas as pd


In [6]:
abcd = pd.Series([1,2,3,4,5])
print(abcd)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [7]:
array = np.array([1,2,3,4,5,6,7,8,9,10])
print("one dimensional array")
print(array)

one dimensional array
[ 1  2  3  4  5  6  7  8  9 10]


In [11]:
array1 = np.array([[1,2,3,4,5],[1,2,3,4,5],[12,34,56,67,1]])
print("Multidemensional array:")
print(array1)


Multidemensional array:
[[ 1  2  3  4  5]
 [ 1  2  3  4  5]
 [12 34 56 67  1]]


In [14]:
abc = np.zeros((4,5))
print("numpy arrayby using Zeros:")
print(abc)

numpy arrayby using Zeros:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [16]:
abc1 = np.ones((5,4))
print("nimpy array by using ones:")
print(abc1)

nimpy array by using ones:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
